// Mocks generated by Mockito 5.3.2 from annotations
// in core/test/pages/watchlist_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/movies.dart' as _i2;
import 'package:series/series.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetWatchlistMovies_0 extends _i1.SmartFake
    implements _i2.GetWatchlistMovies {
  _FakeGetWatchlistMovies_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetMovieWatchListStatus_1 extends _i1.SmartFake
    implements _i2.GetMovieWatchListStatus {
  _FakeGetMovieWatchListStatus_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveMovieWatchlist_2 extends _i1.SmartFake
    implements _i2.SaveMovieWatchlist {
  _FakeSaveMovieWatchlist_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveMovieWatchlist_3 extends _i1.SmartFake
    implements _i2.RemoveMovieWatchlist {
  _FakeRemoveMovieWatchlist_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieState_4 extends _i1.SmartFake implements _i2.MovieState {
  _FakeMovieState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlist_5 extends _i1.SmartFake implements _i3.GetWatchlist {
  _FakeGetWatchlist_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListStatus_6 extends _i1.SmartFake
    implements _i3.GetWatchListStatus {
  _FakeGetWatchListStatus_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlist_7 extends _i1.SmartFake implements _i3.SaveWatchlist {
  _FakeSaveWatchlist_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlist_8 extends _i1.SmartFake
    implements _i3.RemoveWatchlist {
  _FakeRemoveWatchlist_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeriesState_9 extends _i1.SmartFake implements _i3.SeriesState {
  _FakeSeriesState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieWatchlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieWatchlistBloc extends _i1.Mock
    implements _i2.MovieWatchlistBloc {
  MockMovieWatchlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistMovies get getWatchlistMovies => (super.noSuchMethod(
        Invocation.getter(#getWatchlistMovies),
        returnValue: _FakeGetWatchlistMovies_0(
          this,
          Invocation.getter(#getWatchlistMovies),
        ),
      ) as _i2.GetWatchlistMovies);
  @override
  _i2.GetMovieWatchListStatus get getMovieWatchListStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getMovieWatchListStatus),
        returnValue: _FakeGetMovieWatchListStatus_1(
          this,
          Invocation.getter(#getMovieWatchListStatus),
        ),
      ) as _i2.GetMovieWatchListStatus);
  @override
  _i2.SaveMovieWatchlist get saveMovieWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveMovieWatchlist),
        returnValue: _FakeSaveMovieWatchlist_2(
          this,
          Invocation.getter(#saveMovieWatchlist),
        ),
      ) as _i2.SaveMovieWatchlist);
  @override
  _i2.RemoveMovieWatchlist get removeMovieWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeMovieWatchlist),
        returnValue: _FakeRemoveMovieWatchlist_3(
          this,
          Invocation.getter(#removeMovieWatchlist),
        ),
      ) as _i2.RemoveMovieWatchlist);
  @override
  _i2.MovieState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMovieState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.MovieState);
  @override
  _i4.Stream<_i2.MovieState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.MovieState>.empty(),
      ) as _i4.Stream<_i2.MovieState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void add(_i2.MovieEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i2.MovieEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i2.MovieState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i2.MovieEvent>(
    _i5.EventHandler<E, _i2.MovieState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i5.Transition<_i2.MovieEvent, _i2.MovieState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void onChange(_i5.Change<_i2.MovieState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SeriesWatchlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesWatchlistBloc extends _i1.Mock
    implements _i3.SeriesWatchlistBloc {
  MockSeriesWatchlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetWatchlist get getWatchlistSeries => (super.noSuchMethod(
        Invocation.getter(#getWatchlistSeries),
        returnValue: _FakeGetWatchlist_5(
          this,
          Invocation.getter(#getWatchlistSeries),
        ),
      ) as _i3.GetWatchlist);
  @override
  _i3.GetWatchListStatus get getSeriesWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getSeriesWatchListStatus),
        returnValue: _FakeGetWatchListStatus_6(
          this,
          Invocation.getter(#getSeriesWatchListStatus),
        ),
      ) as _i3.GetWatchListStatus);
  @override
  _i3.SaveWatchlist get saveSeriesWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveSeriesWatchlist),
        returnValue: _FakeSaveWatchlist_7(
          this,
          Invocation.getter(#saveSeriesWatchlist),
        ),
      ) as _i3.SaveWatchlist);
  @override
  _i3.RemoveWatchlist get removeSeriesWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeSeriesWatchlist),
        returnValue: _FakeRemoveWatchlist_8(
          this,
          Invocation.getter(#removeSeriesWatchlist),
        ),
      ) as _i3.RemoveWatchlist);
  @override
  _i3.SeriesState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSeriesState_9(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.SeriesState);
  @override
  _i4.Stream<_i3.SeriesState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.SeriesState>.empty(),
      ) as _i4.Stream<_i3.SeriesState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void add(_i3.SeriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i3.SeriesEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.SeriesState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i3.SeriesEvent>(
    _i5.EventHandler<E, _i3.SeriesState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i5.Transition<_i3.SeriesEvent, _i3.SeriesState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void onChange(_i5.Change<_i3.SeriesState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
